from setuptools import setup, find_packages

setup(
    name='tslib',
    version='0.1.1',
    author="Aleksey Glotov",
    description='Library for time series forecast and anomaly detection',
    packages=find_packages(include=["tslib"]),
    #package_dir={"src": "src"},
    package_data={'tslib': ['checkpoints/*.joblib']},
    include_package_data=True,
    install_requires=['certifi==2020.6.20',
                      'cmdstanpy==0.9.5',
                      'convertdate==2.2.2',
                      'cycler==0.10.0',
                      'Cython==0.29.21',
                      'fbprophet==0.7.1',
                      'findspark==1.4.1', 
                      'future==0.18.2',  
                      'holidays==0.10.3',
                      'joblib==0.17.0',
                      'LunarCalendar==0.0.9',
                      'matplotlib==3.3.2',
                      'numpy==1.21.2',
                      'pgeocode==0.2.1',
                      'pyspark==3.0.0',
                      'pystan==2.19.1.1',
                      'python-dateutil==2.8.2',
                      'pytz==2021.3',
                      'retrying==1.3.3',
                      'scikit-learn==0.23.2',
                      'scipy==1.5.2',
                      'setuptools-git==1.2',
                      'six==1.16.0',
                      'scikit-learn==0.23.2',
                      'timezonefinder==4.4.1',
                      'tsfresh==0.18.0',
                      'tqdm==4.50.0',
                      'urllib3==1.25.10',
                      'xlrd==1.2.0',
                      'openpyxl==3.0.6'
                      ],
    project_urls={
        "Bug Tracker": "https://dgitlab01.dvl.mc/analytics/transactions_forecast/-/issues",
    },
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MC licence",
        "Operating System :: OS Independent",
    ],
    python_requires=">=3.7",
)
