NAME: total_transactions
TYPE: all
TRAIN_DATA: "../../../data/atm_transactions/transactions_all_6683.csv"
ATM_REGISTRY_DATA: "../../../data/atm_transactions/atm_info.csv"
RESAMPLING_WINDOW: "1H"
AGG_WINDOW: 4
ID_COL: "name"
TIME_COL: "date"
TIMEZONE: 3
